### ISSUE TITLE
[bug] "Lookyloo.submit() got an unexpected keyword argument 'listing'"

### ISSUE THREAD

**Issue by maaaaz** [Lookyloo/PyLookyloo#12]
Hello there,

I might be misusing this great tool, but it seems that it is currently impossible to enqueue an URL

```
$ lookyloo --query "https://xkcd.com/" --listing
Traceback (most recent call last):
  File "/root/venvs/venvtstpy311/bin/lookyloo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/venvs/venvtstpy311/lib/python3.11/site-packages/pylookyloo/__init__.py", line 24, in main
    url = lookyloo.enqueue(args.query, listing=args.listing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venvs/venvtstpy311/lib/python3.11/site-packages/pylookyloo/api.py", line 101, in enqueue
    return self.submit(quiet=quiet, url=url, document=document, document_name=document_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Lookyloo.submit() got an unexpected keyword argument 'listing'
```

```
$ lookyloo --query "https://xkcd.com/"
Traceback (most recent call last):
  File "/root/venvs/venvtstpy311/bin/lookyloo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/venvs/venvtstpy311/lib/python3.11/site-packages/pylookyloo/__init__.py", line 24, in main
    url = lookyloo.enqueue(args.query, listing=args.listing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venvs/venvtstpy311/lib/python3.11/site-packages/pylookyloo/api.py", line 101, in enqueue
    return self.submit(quiet=quiet, url=url, document=document, document_name=document_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Lookyloo.submit() got an unexpected keyword argument 'listing'
```

Here is the stack I am using:
```
$ uname -mrs
Linux 6.1.0-kali5-amd64 x86_64

$ pip freeze
certifi==2022.12.7
charset-normalizer==3.0.1
idna==3.4
pycryptodome==3.17
pylookyloo==1.18.0
requests==2.28.2
urllib3==1.26.14

$ python3 -V
Python 3.11.2

$ cat /etc/issue*
Kali GNU/Linux Rolling \n \l

Kali GNU/Linux Rolling
```

Cheers!

**Comment by Rafiot** [comment]
Woops, right, sorry for that, I mixed-up some parameters, expect a fix in a few min.

**Comment by Rafiot** [comment]
Fixed by: https://github.com/Lookyloo/PyLookyloo/commit/9cbadd60255ae39c28673176222235eaa4c67e59 (and in v1.18.1)

**Comment by maaaaz** [comment]
Thanks, you rock !

Not related to this bug, but there's a **DepreciationWarning** in the `enqueue_list.py` example:

```
$ cat list.txt
https://xkcd.com
https://google.com

$ python3 -Wall enqueue_list.py
To process: 2
https://xkcd.com
/tmp/enqueue_list.py.1:35: DeprecationWarning: Please use submit instead.
  permaurl = lookyloo.enqueue(url, listing=False)
Enqueued: https://xkcd.com - Permaurl: https://lookyloo.circl.lu/tree/66de93e2-18fd-47de-b238-37fcec83f7cd
https://google.com
/tmp/enqueue_list.py.1:35: DeprecationWarning: Please use submit instead.
  permaurl = lookyloo.enqueue(url, listing=False)
Enqueued: https://google.com - Permaurl: https://lookyloo.circl.lu/tree/35f36a30-bd2f-4550-bbd5-4012c5fc263b
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=2, type=1, proto=6, laddr=('192.168.75.137', 49380), raddr=('185.194.94.89', 443)>
```

**Comment by Rafiot** [comment]
right, I left the old call for testing and didn't replace it... doing it now. Thanks!
